Mini-game System
CCC-Development/DoodleMyNoodle pull request #189
Opened 2020-11-01 15:52 UTC by alex534488

- UI utilise maintenant une state machine
- Quand on utilise un item, on entre dans le state parameter selection de la state machine du UI qui gère les transitions vers des states nous permettant d'obtenir les paramètres nécessaires (tile selection, entity selection, minigames)
- Ajout d'un minigame manager pour faire les requêtes de minigames.
- MiniGameController est la classe de base des scripts qui controle les minigames, permet de facilement les Start et les gèrer
- Création d'une scène de test de minigames dans lequel tous les minigames sont en mode "Debug"
- Nouveau component sur les items qui s'appel ItemAuth, contient le ItemVisualInfo et le MiniGame voulu au besoin.
- ItemInfoBank est maintenant seulement un intermediaire utility pour acceder au bon prefab et au bon ItemAuth avec un SimAssetID. Détient une référence Fallback dans les cas ou ont a pas de ItemAuth sur l'item.
- MiniGame définit par un scriptable object Définition qui contient également un autre scriptable object Description. Definition c'est la base genre prefab, nom, etc. et Description c'est les paramètres genre Difficulté, Vitesse etc.
- Refactor dans les GameActionsParameter pour enlever les index qui n'étaient pas utiles et ajoutait de la complexité pour rien
- D'autres ajustements à gauche et à droite pour que tout fonctionne avec les changements décrit plus haut.

2020-11-03 03:24 UTC, msfredb7 requested changes

2020-11-03 03:24 UTC, msfredb7 commented on DoodleMyNoodle/Assets/Code/Simulation.Game/GameAction/ParameterTypes/GameActionParameterMiniGame.cs
> +        public int2 MiniGameLocation;
On ne devrait pas avoir à mettre ça ici. La GameAction.ParameterDescription, c'est pour que les gameactions puisse indiquer les particularité du paramètre s'il y en a. 

Dans notre cas, c'est une certitude que la gameaction est fait pour être placé sur le pawn donc ça ne devrait pas être nécessaire.

Dans MiniGameState.cs, à la ligne 13, en fait c'est que le state devrait pouvoir trouver la position du pawn en question par lui-même (ou le recevoir en paramètre)

2020-11-03 03:24 UTC, msfredb7 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/MiniGames/MiniGameManager.cs
> +            _currentMiniGameCallback.Invoke(MiniGameResultData);
On devrait tu loggé une erreur ici ?

2020-11-03 03:24 UTC, msfredb7 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/MiniGames/MiniGameManager.cs
> +                // can't start mini-game, complete it immediatly
copy-pasta de commentaire

2020-11-03 03:24 UTC, msfredb7 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/MiniGames/MiniGameManager.cs
> +            miniGameController.StartMiniGame(miniGameDefinition.CustomDescription, delegate(GameActionParameterMiniGame.Data resultData)
Le callback devrait être ``Action<GameAction.ParameterData>`` et non ``Action<GameActionParameterMiniGame.Data>``.

tu pourrais simplifier cette ligne de code à ça:
``miniGameController.StartMiniGame(miniGameDefinition.CustomDescription, onCompleteCallback);``

2020-11-03 03:24 UTC, msfredb7 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/MiniGames/MiniGameBaseController.cs
> +    protected T GetMiniGameData<T>() where T : MiniGameDescriptionBase
GetMiniGameDescription<T> ?

2020-11-03 03:24 UTC, msfredb7 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/MiniGames/MiniGameBaseController.cs
> +    public virtual void OnComplete()
J'ai l'impression que 'Complete()' serait plus juste que 'OnComplete()'. Les fonctions qui commence en OnX, c'est souvent des listener d'event genre ``button.clicked = OnClick``

2020-11-03 03:24 UTC, msfredb7 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/MiniGames/MiniGameBaseController.cs
> +        }
J'suis pas sur de comprendre pourquoi on restart la minigame si on est complète. Ça feel comme un hack.

2020-11-03 03:24 UTC, msfredb7 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/MiniGames/MiniGameBaseController.cs
> +    public TextMeshPro DebugDisplay;
Au lieu d'incruster des trucs de débug dans la classe de base, ça serait p-e plus clean de se faire un DebugMiniGameLauncher. Il viendrais remplacer ton MiniGameManager dans ta scène de test. Tu pourrais linké le prefab du minigame et faire 'Start' ou qqchose du genre.

Comme ça, le 'MiniGameBaseController' pourrait ne pas être au courant de si c'est débug ou pas.

2020-11-03 03:24 UTC, msfredb7 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/MiniGames/CustomMiniGames/MiniGameClickTiming.cs
> +    }
Au lieux d'avoir 2x "GetResult", on devrait p-e juste ajouter un beau ``override string ToString()`` dans le GameActionParameter. En mode normal, on utilise le param data, en mode debug on fait Debug.Log(paramData.ToString())

2020-11-03 03:24 UTC, msfredb7 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/MiniGames/CustomMiniGames/MiniGameClickTiming.cs
> +        yield return MiniGameLoop();
On devrait faire un while au lieux d'un appel récursif. À chaque appel, ça réalloue de la mémoire pour de nouvelle variable temporaire. Et c'est plus dure à lire.

2020-11-03 03:24 UTC, msfredb7 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/MiniGames/MiniGameBaseController.cs
> +        _currentGameLoop = StartCoroutine("MiniGameLoop");
Tu peux remplacer ``"MiniGameLoop"`` par ``MiniGameLoop()``

2020-11-07 15:25 UTC, alex534488 commented on DoodleMyNoodle/Assets/Code/Simulation.Game/GameAction/GameAction.cs
> -        }
C'est juste que en se moment, ce serait hyper chiant de conserver l'ID alors qu'en fait du point de vue des game actions il s'agit de l'index. Faudrait revoir entièrement ce principe parce que je vois pas le point d'avoir ca si l'utilisation dans les game actions ce fait comme suit. En se moment, l'ID des paramètres étaient même pas utilisé :

useData.TryGetParameter(0, out GameActionParameterTile.Data paramTile)

2020-11-07 15:27 UTC, alex534488 commented on DoodleMyNoodle/Assets/Code/Simulation.Game/GameAction/ParameterTypes/GameActionParameterMiniGame.cs
> +        public int2 Position;
Ok, effectivement ca fait pas mal plus de sens que d'avoir un paramètre de minigame.

2020-11-07 15:31 UTC, alex534488 commented on DoodleMyNoodle/Assets/Code/Simulation.Game/MiniGames/MiniGameDefinitionBase.cs
> +    public GameObject Prefab;
J'vais changer pour un MonoBehavior comme ta dit plus haut de toutes facons, donc on va link un prefab direct. Ce champ va donc disparaitre.

2020-11-07 15:41 UTC, alex534488 commented on DoodleMyNoodle/Assets/Code/Simulation.Game/GameAction/ParameterTypes/GameActionParameterMiniGame.cs
> +        public int2 MiniGameLocation;
À ce moment la comment faire la distinction entre un minigame qui doit être fait sur une case adjacente, sur un npc au loin, sur personnage du joueur, ou litérallement fullscreen. Faut bien que la gameaction donne un peu d'info par rapport à comment l'abilité est sensé se faire.

2020-11-07 15:53 UTC, alex534488 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/MiniGames/MiniGameManager.cs
> +            miniGameController.StartMiniGame(miniGameDefinition.CustomDescription, delegate(GameActionParameterMiniGame.Data resultData)
Le problème avec la simplification des paramètres et ici en retourner qu'un c'est si on a un minigame qui retourne un vecteur et un succès rate dans le même jeu (ex: envoyer un joystick dans la bonne direction au bon moment -> direction, timing, precision = 3 données)

2020-11-07 16:03 UTC, alex534488 commented on DoodleMyNoodle/Assets/Code/Simulation.Game/GameAction/ParameterTypes/GameActionParameterMiniGame.cs
> +        public int2 MiniGameLocation;
Après en avoir discuter, on élimine complètement la position pour simplement toujours spawn sur la position du joueur.

2020-11-07 16:32 UTC, alex534488 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/MiniGames/MiniGameBaseController.cs
> +        }
Le seul moment ou on call Complete alors que le minigame est déja complété c'est en debug. Je vais rajouter un commentaire

2020-11-07 16:42 UTC, alex534488 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/MiniGames/MiniGameBaseController.cs
> +        }
On veut figer le mini-game lorsqu'il est complété. C'est ce qu'il se produit en se moment. Ensuite, il faut pouvoir le redémarrer mais uniquement lorsque l'utilisateur veut vraiment. On laisse donc soin au classe enfant de décider comment le mini-game peut être complété et donc redémarrer, j'ai essayer de changer un peu, mais c'est avec ce code que ca marche le mieu donc j'vais laisser comme ca pour l'instant.

2020-11-14 20:04 UTC, alex534488 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/MiniGames/MiniGameBaseController.cs
> +    public TextMeshPro DebugDisplay;
J'vais laisser comme ca pour l'instant et me faire une tache pour ca. https://github.com/CCC-Development/DoodleMyNoodle/issues/190

2020-11-14 20:12 UTC, alex534488 commented
Ce que j'ai fait au final, c'est une gestion des paramètres de Game Action sous forme de "requête". Ca ressemble pas mal à ce que j'avais fait, mais maintenant on fait une gestion ou l'on essai de trouvé un mini-game correspondant à des paramètres plus générique selon ce qui est rentré en data sur l'item. Au final, les paramètres traités ne sont plus considérer et on passe à la suite jusqu'à se qu'on géré tous les paramètres. Au niveau du UI, on fait des back n forth entre ParameterSelectionState et GameActionRequestState pour bien assurer le passage d'une requête de data d'une liste de paramètre à une autre.

Dans le cas ou on trouve pas de requête (aka mini game ou autre), on peut passer par des systèmes externes qui traite un peu comme on le faisait avant (ex : TileHighlightManager)

2020-11-15 18:53 UTC, msfredb7 requested changes

2020-11-15 18:53 UTC, msfredb7 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/StateMachine/GameActionRequestState.cs
> +                GameActionRequestManager.Instance.RequestData(Cache.LocalPawnPosition.ToUnityVec(), itemAuth.FindRequestDefinitionForParameters(ParameterDescriptionList),
Tu peux utiliser LocalPawnPositionFloat au lieux de LocalPawnPosition.ToUnityVec()

2020-11-15 18:53 UTC, msfredb7 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/StateMachine/ParameterSelectionState.cs
> +            UIStateMachine.Instance.TransitionTo(UIState.StateTypes.GameActionRequest, _itemEntity, newParameterList.ToArray());
J'laisserais un commentaire pour dire qu'on ne fait que "tempter" de remplir tous les params. En pratique, c'est souvent 1 seul param qui va être remplie par le survey

2020-11-15 18:53 UTC, msfredb7 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/StateMachine/GameActionRequestState.cs
> +                GameActionRequestManager.Instance.RequestData(Cache.LocalPawnPosition.ToUnityVec(), itemAuth.FindRequestDefinitionForParameters(ParameterDescriptionList),
Commme on a discuter, on pourrait splitter ça en:
```
var specificSurvey = itemAuth.FindRequestDefinitionForParameters(ParameterDescriptionList);
if(specificSurvey != null)
{
    GameActionRequestManager.Instance.RequestData(... specificSurvey )
}
else
{
    GameActionRequestManager.Instance.RequestDataWithDefaultSurvey(...)
}

```

2020-11-15 18:53 UTC, msfredb7 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/MiniGames/GameActionRequestManager.cs
> +    public void RequestExternalData(GameAction.ParameterDescription[] parameters)
On peut delete cette fonction si on se fait un Survey pour la TileSelection qui utilise le TileHighlightManager à l'interne

2020-11-15 18:53 UTC, msfredb7 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/MiniGames/GameActionRequestManager.cs
> +
On peut ajouter les 'default' surveys ici

2020-11-15 18:53 UTC, msfredb7 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/MiniGames/MiniGameBaseController.cs
> +public abstract class GameActionDataRequestBaseController : MonoBehaviour
On peut fusionner cette classe et la DefinitionBase. (Bref juste delete la DefinitionBase et utiliser ``SurveyControllerBase`` partout

2020-11-15 18:53 UTC, msfredb7 commented on DoodleMyNoodle/Assets/Code/Game/Gameplay/Presentation/MiniGames/MiniGameBaseController.cs
> +    public virtual void Complete()
Au lieux d'avoir ``protected abstract List<GameAction.ParameterData> GetResult();``, ça serait p-e plus intuitif d'ajouter ``List<GameAction.ParameterData> result`` en paramètre dans la fonction ici.

2020-11-15 21:15 UTC, merged